// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pomidor;

namespace Pomidor.Migrations
{
    [DbContext(typeof(PomoDbContext))]
    [Migration("20190818113814_removeRecreation")]
    partial class removeRecreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pomidor.Pet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Experience");

                    b.Property<int>("Level");

                    b.Property<int>("TypeID");

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("TypeID");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Pomidor.Pomidor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Duration");

                    b.Property<DateTime>("EndTime");

                    b.Property<bool>("PrizeIssued");

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.ToTable("Pomidors");
                });

            modelBuilder.Entity("Pomidor.TypeOfPet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImgFolder");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.HasKey("ID");

                    b.ToTable("TypeOfPets");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ImgFolder = "Cat",
                            Name = "Cat",
                            Price = 50
                        },
                        new
                        {
                            ID = 2,
                            ImgFolder = "Hog",
                            Name = "Hog",
                            Price = 100
                        });
                });

            modelBuilder.Entity("Pomidor.Pet", b =>
                {
                    b.HasOne("Pomidor.TypeOfPet", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
