// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pomidor;

namespace Pomidor.Migrations
{
    [DbContext(typeof(PomoDbContext))]
    [Migration("20190327153838_pp")]
    partial class pp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pomidor.Pet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level");

                    b.Property<int>("TypeID");

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("TypeID");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Pomidor.Pomidor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("Duration");

                    b.Property<DateTime>("EndTime");

                    b.Property<bool>("PrizeIssued");

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.ToTable("Pomidors");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pomidor");
                });

            modelBuilder.Entity("Pomidor.TypeOfPet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Img");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("TypeOfPets");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Cat"
                        });
                });

            modelBuilder.Entity("Pomidor.Recreation", b =>
                {
                    b.HasBaseType("Pomidor.Pomidor");

                    b.HasDiscriminator().HasValue("Recreation");
                });

            modelBuilder.Entity("Pomidor.Pet", b =>
                {
                    b.HasOne("Pomidor.TypeOfPet", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
